name: RSpec

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  spec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.6', '2.7', '3.0', '3.1', '3.2']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Specs
      run: bundle exec rake spec
